/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT4_TPM1CH0SRC_TPM1_CH0 0x00u /*!<@brief TPM1 channel 0 input capture source select: TPM1_CH0 signal */
#define SOPT5_UART0RXSRC_UART_RX 0x00u  /*!<@brief UART0 receive data source select: UART0_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u  /*!<@brief UART0 transmit data source select: UART0_TX pin */

/*! @name PORTA2 (number 28), J1[4]/D1/UART0_TX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                                /* @} */

/*! @name PORTA1 (number 27), J1[2]/D0/UART0_RX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 1U     /*!<@brief PORTA pin index: 1 */
                                                /* @} */

/*! @name PORTC7 (number 64), M_IN1
  @{ */
#define BOARD_INITPINS_M_IN1_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_M_IN1_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_M_IN1_PIN 7U     /*!<@brief PORTC pin index: 7 */
                                        /* @} */

/*! @name PORTC0 (number 55), M_IN2
  @{ */
#define BOARD_INITPINS_M_IN2_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_M_IN2_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_M_IN2_PIN 0U     /*!<@brief PORTC pin index: 0 */
                                        /* @} */

/*! @name PORTC3 (number 58), M_IN3
  @{ */
#define BOARD_INITPINS_M_IN3_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_M_IN3_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_M_IN3_PIN 3U     /*!<@brief PORTC pin index: 3 */
                                        /* @} */

/*! @name PORTC4 (number 61), M_IN4
  @{ */
#define BOARD_INITPINS_M_IN4_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_M_IN4_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_M_IN4_PIN 4U     /*!<@brief PORTC pin index: 4 */
                                        /* @} */

/*! @name PORTE30 (number 22), J10[11]
  @{ */
#define BOARD_INITPINS_IR_SS5_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_IR_SS5_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_IR_SS5_PIN 30U    /*!<@brief PORTE pin index: 30 */
                                         /* @} */

/*! @name PORTE29 (number 21), J10[9]
  @{ */
#define BOARD_INITPINS_IR_SS4_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_IR_SS4_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_IR_SS4_PIN 29U    /*!<@brief PORTE pin index: 29 */
                                         /* @} */

/*! @name PORTE23 (number 16), J10[7]
  @{ */
#define BOARD_INITPINS_IR_SS3_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_IR_SS3_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_IR_SS3_PIN 23U    /*!<@brief PORTE pin index: 23 */
                                         /* @} */

/*! @name PORTE22 (number 15), J10[5]
  @{ */
#define BOARD_INITPINS_IR_SS2_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_IR_SS2_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_IR_SS2_PIN 22U    /*!<@brief PORTE pin index: 22 */
                                         /* @} */

/*! @name PORTE21 (number 14), J10[3]
  @{ */
#define BOARD_INITPINS_IR_SS1_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_IR_SS1_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_IR_SS1_PIN 21U    /*!<@brief PORTE pin index: 21 */
                                         /* @} */

/*! @name PORTA13 (number 33), J2[2]/D8
  @{ */
#define BOARD_INITPINS_LCD_RS_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_LCD_RS_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_LCD_RS_PIN 13U    /*!<@brief PORTA pin index: 13 */
                                         /* @} */

/*! @name PORTD5 (number 78), J2[4]/D9
  @{ */
#define BOARD_INITPINS_LCD_EN_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LCD_EN_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LCD_EN_PIN 5U     /*!<@brief PORTD pin index: 5 */
                                         /* @} */

/*! @name PORTA4 (number 30), J1[10]/D4
  @{ */
#define BOARD_INITPINS_LCD_D4_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_LCD_D4_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_LCD_D4_PIN 4U     /*!<@brief PORTA pin index: 4 */
                                         /* @} */

/*! @name PORTA5 (number 31), J1[12]/D5
  @{ */
#define BOARD_INITPINS_LCD_D5_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_LCD_D5_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_LCD_D5_PIN 5U     /*!<@brief PORTA pin index: 5 */
                                         /* @} */

/*! @name PORTC8 (number 65), J1[14]
  @{ */
#define BOARD_INITPINS_LCD_D6_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LCD_D6_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LCD_D6_PIN 8U     /*!<@brief PORTC pin index: 8 */
                                         /* @} */

/*! @name PORTC9 (number 66), J1[16]
  @{ */
#define BOARD_INITPINS_LCD_D7_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LCD_D7_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LCD_D7_PIN 9U     /*!<@brief PORTC pin index: 9 */
                                         /* @} */

/*! @name PORTD2 (number 75), J2[8]/D11
  @{ */
#define BOARD_INITPINS_R_ENCODER_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_R_ENCODER_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_R_ENCODER_PIN 2U     /*!<@brief PORTD pin index: 2 */
                                            /* @} */

/*! @name PORTD3 (number 76), J2[10]/D12
  @{ */
#define BOARD_INITPINS_L_ENCODER_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_L_ENCODER_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_L_ENCODER_PIN 3U     /*!<@brief PORTD pin index: 3 */
                                            /* @} */

/*! @name PORTE2 (number 3), J9[9]
  @{ */
#define BOARD_INITPINS_ULTRA_TRIG_R_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_ULTRA_TRIG_R_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_ULTRA_TRIG_R_PIN 2U     /*!<@brief PORTE pin index: 2 */
                                               /* @} */

/*! @name PORTE3 (number 4), J9[11]
  @{ */
#define BOARD_INITPINS_ULTRA_TRIG_F_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_ULTRA_TRIG_F_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_ULTRA_TRIG_F_PIN 3U     /*!<@brief PORTE pin index: 3 */
                                               /* @} */

/*! @name PORTA16 (number 36), J2[9]
  @{ */
#define BOARD_INITPINS_ULTRA_TRIG_L_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_ULTRA_TRIG_L_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_ULTRA_TRIG_L_PIN 16U    /*!<@brief PORTA pin index: 16 */
                                               /* @} */

/*! @name PORTE31 (number 23), J2[13]
  @{ */
#define BOARD_INITPINS_ULTRA_ECHO_R_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_ULTRA_ECHO_R_PIN 31U    /*!<@brief PORTE pin index: 31 */
                                               /* @} */

/*! @name PORTD0 (number 73), J2[6]/D10
  @{ */
#define BOARD_INITPINS_ULTRA_ECHO_F_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_ULTRA_ECHO_F_PIN 0U     /*!<@brief PORTD pin index: 0 */
                                               /* @} */

/*! @name PORTC2 (number 57), J10[10]/A4
  @{ */
#define BOARD_INITPINS_ULTRA_ECHO_L_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_ULTRA_ECHO_L_PIN 2U     /*!<@brief PORTC pin index: 2 */
                                               /* @} */

/*! @name PORTE1 (number 2), MPU_SCL
  @{ */
#define BOARD_INITPINS_MPU_SCL_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_MPU_SCL_PIN 1U     /*!<@brief PORTE pin index: 1 */
                                          /* @} */

/*! @name PORTE0 (number 1), J2[18]/D14
  @{ */
#define BOARD_INITPINS_MPU_SDA_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_MPU_SDA_PIN 0U     /*!<@brief PORTE pin index: 0 */
                                          /* @} */

/*! @name PORTB18 (number 53), D3[1]/LEDRGB_RED
  @{ */
#define BOARD_INITPINS_LED_RED_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LED_RED_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LED_RED_PIN 18U    /*!<@brief PORTB pin index: 18 */
                                          /* @} */

/*! @name PORTB19 (number 54), D3[4]/LEDRGB_GREEN
  @{ */
#define BOARD_INITPINS_LED_GREEN_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LED_GREEN_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LED_GREEN_PIN 19U    /*!<@brief PORTB pin index: 19 */
                                            /* @} */

/*! @name PORTD4 (number 77), J1[6]/D2
  @{ */
#define BOARD_INITPINS_WCET_MSR_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_WCET_MSR_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_WCET_MSR_PIN 4U     /*!<@brief PORTD pin index: 4 */
                                           /* @} */

/*! @name PORTE5 (number 6), J9[15]
  @{ */
#define BOARD_INITPINS_KEY_FRONT_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_KEY_FRONT_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_KEY_FRONT_PIN 5U     /*!<@brief PORTE pin index: 5 */
                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
